name: trvl

services:
  # nextjs service
  trvl_front_app:
    container_name: trvl_front_app
    image: trvl_front_app:1.0.0
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
    - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - trvl_api_app

  # flask service
  trvl_api_app:
    container_name: trvl_api_app
    image: trvl_api_app:1.0.0
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  # db service
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
